spring:

  security:
    user:
      name: javed
      password: j@123

  datasource:
    url: jdbc:postgresql://localhost:5432/smartjobtracker
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.example.com
    port: 587
    username: demo
    password: demo

server:
  port: 8080

jwt:
  secret: "I am creating abra ka dabra the magician s3cr3t k3y"
  expiration: 86400000